import type { NextPage } from 'next'
import Head from "next/head";
import AccountDetailsView from "../views/accountDetailsView";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>CandyMachine Check</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AccountDetailsView />
    </div>
  );
};

export default Home
